#!/bin/bash
#
# Name: WISH = Wifi Shell
#
# Description: This program allows you to connect to the wifi using iw, ip command and
# wpa_ supplicant/wpa_passphrase into terminal.
# 
# Dependencies: iw , wpa_supplicant , dhclient
#

# Variables
DEVICE="$(iw dev | grep Interface | awk '{print$2}')"
wpas="wpa_supplicant -B -D wext -i"

[ -z $HOME/wifi ] || mkdir "$HOME"/wifi
rfkill unblock wifi
iw $DEVICE scan | grep SSID | awk '{print$2}' # bloated
  sleep 1
  echo -e \\n "Type an SSID"
  read SSID
[ -z $HOME/wifi/$SSID ] || mkdir "$HOME/wifi" 
  $wpas $DEVICE -c $HOME/wifi/$SSID
  echo "Type a password" 
  wpa_passphrase $SSID >> $HOME/wifi/$SSID
  $wpas $DEVICE -c $HOME/wifi/$SSID
 dhclient
